//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePlatforms_EX_StasIvan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estates()
        {
            this.OnlinePlatforms = new HashSet<OnlinePlatforms>();
        }
    
        public int id_Estate { get; set; }
        public string NameEstate { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> YearBuilding { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> PriceEstate { get; set; }
        public string Purchase { get; set; }
    
        public virtual Facilities Facilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlinePlatforms> OnlinePlatforms { get; set; }
    }
}
