//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePlatforms_EX_StasIvan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilities
    {
        public int id_Estate { get; set; }
        public string NameBoon { get; set; }
        public Nullable<decimal> CountService { get; set; }
        public Nullable<System.DateTime> StartService { get; set; }
        public Nullable<System.DateTime> EndService { get; set; }
    
        public virtual Estates Estates { get; set; }
    }
}
