//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePlatforms_EX_StasIvan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineOrderHomesEntities : DbContext
    {
        private static OnlineOrderHomesEntities _context;

        public static OnlineOrderHomesEntities GetContext()
        {
            if (_context == null)
                _context = new OnlineOrderHomesEntities();
            return _context;
        }
        public OnlineOrderHomesEntities()
            : base("name=OnlineOrderHomesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Estates> Estates { get; set; }
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<OnlinePlatforms> OnlinePlatforms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
