//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePlatforms_EX_StasIvan
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePlatforms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlinePlatforms()
        {
            this.Users = new HashSet<Users>();
        }
    
        public string NamePlatform { get; set; }
        public string Site { get; set; }
        public Nullable<int> CountUsers { get; set; }
        public string Telephone { get; set; }
        public string AuthorLogin { get; set; }
        public Nullable<int> id_Estate { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Estates Estates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
